<a href="https://colab.research.google.com/github/PrathushaRekha/Disease-Diagnosis-System-Using-Human-Nail-Image/blob/main/nail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
[[2.4984448e-04 7.0662162e-04 2.1682821e-04 1.6972199e-04 9.9644611e-05 9.8324293e-01 6.6723401e-04 5.1942193e-03 4.8860402e-05 2.2987171e-05 2.5026349e-03 3.5574668e-04 9.6228459e-06 4.4953203e-04 1.4495164e-04 5.1868602e-04 5.3999224e-03]]

In [ ]:
from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from glob import glob
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
imageSize = [224, 224]

trainPath = r"/content/drive/MyDrive/Dataset/train"

testPath = r"/content/drive/MyDrive/Dataset/test"


In [ ]:
vgg = VGG16(input_shape=imageSize + [3], weights='imagenet',include_top=False)

In [ ]:
for layer in vgg.layers:
  layer.trainable = False

In [ ]:
# our layers - you can add more if you want
x = Flatten()(vgg.output)

In [ ]:
prediction = Dense(17, activation='softmax')(x)

In [ ]:
# create a model object
model = Model(inputs=vgg.input, outputs=prediction)

In [ ]:
# view the structure of the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv1 (Conv2D)           │ (None, 224, 224, 64)   │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv2 (Conv2D)           │ (None, 224, 224, 64)   │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_pool (MaxPooling2D)      │ (None, 112, 112, 64)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv1 (Conv2D)           │ (None, 112, 112, 128)  │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv2 (Conv2D)           │ (None, 112, 112, 128)  │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_pool (MaxPooling2D)      │ (None, 56, 56, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv1 (Conv2D)           │ (None, 56, 56, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv2 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv3 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_pool (MaxPooling2D)      │ (None, 28, 28, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv1 (Conv2D)           │ (None, 28, 28, 512)    │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv2 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv3 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_pool (MaxPooling2D)      │ (None, 14, 14, 512)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv1 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv2 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv3 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_pool (MaxPooling2D)      │ (None, 7, 7, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 17)             │       426,513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,141,201 (57.76 MB)

 Trainable params: 426,513 (1.63 MB)

 Non-trainable params: 14,714,688 (56.13 MB)

In [ ]:
# tell the model what cost and optimization method to use
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy'], run_eagerly=True
)

In [ ]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [ ]:
training_set = train_datagen.flow_from_directory(trainPath,
                                                 target_size = (224, 224),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory(testPath,
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 655 images belonging to 17 classes.
Found 183 images belonging to 17 classes.


In [ ]:
training_set.class_indices

{'Darier_s disease': 0,
 'Muehrck-e_s lines': 1,
 'aloperia areata': 2,
 'beau_s lines': 3,
 'bluish nail': 4,
 'clubbing': 5,
 'eczema': 6,
 'half and half nailes (Lindsay_s nails)': 7,
 'koilonychia': 8,
 'leukonychia': 9,
 'onycholycis': 10,
 'pale nail': 11,
 'red lunula': 12,
 'splinter hemmorrage': 13,
 'terry_s nail': 14,
 'white nail': 15,
 'yellow nails': 16}

In [ ]:
len(training_set)

21

In [ ]:
import sys
# fit the model
r = model.fit(
  training_set,
  validation_data=test_set,
  epochs=20,
  steps_per_epoch=len(training_set),
  validation_steps=len(test_set))

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 232s 10s/step - accuracy: 0.0574 - loss: 3.6906 - val_accuracy: 0.2350 - val_loss: 2.6335
Epoch 2/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 16s 727ms/step - accuracy: 0.2351 - loss: 2.4650 - val_accuracy: 0.3497 - val_loss: 2.2406
Epoch 3/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 20s 739ms/step - accuracy: 0.3343 - loss: 2.2790 - val_accuracy: 0.4317 - val_loss: 1.8304
Epoch 4/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 16s 750ms/step - accuracy: 0.4228 - loss: 1.8929 - val_accuracy: 0.4918 - val_loss: 1.6479
Epoch 5/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 20s 746ms/step - accuracy: 0.4652 - loss: 1.7380 - val_accuracy: 0.5956 - val_loss: 1.3613
Epoch 6/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 21s 776ms/step - accuracy: 0.5521 - loss: 1.4828 - val_accuracy: 0.5902 - val_loss: 1.3285
Epoch 7/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 16s 743ms/step - accuracy: 0.6009 - loss: 1.3939 - val_accuracy: 0.6503 - val_loss: 1.3295
Epoch 8/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 16s 750ms/step - accuracy: 0.6113 - loss: 1.4377 - val_accur

In [ ]:
#save the model
model.save('vgg-16-nail-disease.keras')

In [ ]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np

In [ ]:
#load saved model file
model=load_model('vgg-16-nail-disease.keras')

In [ ]:
#load one random image from local system
img=image.load_img('/content/drive/MyDrive/Dataset/test/clubbing/10.PNG',target_size=(224,224))

In [ ]:
#convert image to array format
x = image.img_to_array(img)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x.shape

(224, 224, 3)

In [ ]:
x = np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
print(img_data.shape)

(1, 224, 224, 3)


In [ ]:
model.predict(img_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 583ms/step


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 8.0221415e-25, 1.9526882e-33,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00]], dtype=float32)

In [ ]:
output=np.argmax(model.predict(img_data), axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


In [ ]:
[[2.4984448e-04 7.0662162e-04 2.1682821e-04 1.6972199e-04 9.9644611e-05 9.8324293e-01 6.6723401e-04 5.1942193e-03 4.8860402e-05 2.2987171e-05 2.5026349e-03 3.5574668e-04 9.6228459e-06 4.4953203e-04 1.4495164e-04 5.1868602e-04 5.3999224e-03]]

In [ ]:
import numpy as np

output=np.argmax([[2.4984448e-04, 7.0662162e-04, 2.1682821e-04, 1.6972199e-04, 9.9644611e-05, 9.8324293e-01, 6.6723401e-04, 5.1942193e-03, 4.8860402e-05, 2.2987171e-05, 2.5026349e-03, 3.5574668e-04, 9.6228459e-06, 4.4953203e-04, 1.4495164e-04, 5.1868602e-04, 5.3999224e-03]], axis=1)

In [ ]:
print(output)

[5]


In [ ]:
display(output)

array([5])

In [ ]:
index=['Darier_s disease', 'Muehrck-e_s lines', 'aloperia areata', 'beau_s lines', 'bluish nail',
       'clubbing','eczema','half and half nailes (Lindsay_s nails)','koilonychia','leukonychia',
       'onycholycis','pale nail','red lunula','splinter hemmorrage','terry_s nail','white nail','yellow nails']
result = str(index[output[0]])
result

'splinter hemmorrage'